const ACTIONS = {
  GET_NOTES: 'GET_NOTES',
  SEARCH_NOTES: 'SEARCH_NOTES',
  SAVE_NOTE: 'SAVE_NOTE',
};

const GETTERS = {
  FILTERED_NOTES: 'FILTERED_NOTES',
};

const MUTATIONS = {
  GET_NOTES_SUCCESS: 'GET_NOTES_SUCCESS',
  SEARCH_NOTES_SUCCESS: 'SEARCH_NOTES_SUCCESS',
  SAVE_NOTE_SUCCESS: 'SAVE_NOTE_SUCCESS',
};

export {
  ACTIONS,
  GETTERS,
  MUTATIONS,
};
